### ISSUE TITLE
README 수정해주세요

### ISSUE THREAD

**Issue by Manicarus** [alphalife3314/Mentoring_Shift#3]
출석부(출석/숙제완료:1 결석/숙제완료:0.25 출석/숙제미흡:0.5 결석/숙제미흡:0)

이 부분은 **리스트**로 정리해주세요
- 출석 / 숙제완료 : 1 
- 출석 / 숙제미흡 : 0.5 
- 결석 / 숙제완료 : 0.25 
- 결석 / 숙제미흡 : 0

그리고 BJCloud 깃허브 Wiki에 규정을 업데이트 했습니다. 링크 걸어주세요.
[보정 구름 멘토링 규정](https://github.com/Manicarus/BJCloud/wiki/멘토링-규칙)

**Comment by alphalife3314** [comment]
수정 완료하였습니다.
